import {
  Bot,
  ClipboardSignature,
  Database,
  FileSpreadsheet,
  Globe,
  Layers,
  Network,
  Scale,
  Server,
  ServerCog,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Store,
  Truck,
  Wrench,
  type LucideIcon,
} from "lucide-react";
import type { ProjectIcon } from "@/types/project";

export const projectIcons: Record<ProjectIcon, LucideIcon> = {
  Bot,
  ClipboardSignature,
  Database,
  FileSpreadsheet,
  Globe,
  Layers,
  Network,
  Scale,
  Server,
  ServerCog,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Store,
  Truck,
  Wrench,
};
